---
version: "3"
services:
  shoppy:
    image: nagesh2devops/one:shoppy_image
    deploy:
      replicas: 2
    ports:
      - "8080:8080"
    volumes:
      - shoppyvolume:/shoppy  
    networks:
      - shoppynetwork

volumes:
  shoppyvolume:
   
networks:
  shoppynetwork:
    driver: bridge

