---
version: "3"
services:
  shoppy:
    container_name: shoppy-cont
    build: .
    ports:
      - "2211:8080"
    volumes:
      - shoppyvolume:/shoppy  
    network:
      - shoppynetwork

volumes:
  shoppyvolume:
   
networks:
  shoppynetwork:
    driver: bridge

